// Import Workbox libraries
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache all the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache API requests
registerRoute(
    ({ url }) => url.origin === 'https://your-api-endpoint.com',
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            // Add plugins as needed
        ],
    })
);

// You can add additional caching strategies as needed

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
